# https://taskfile.dev

version: '3'

vars:
  CC: clang
  CC_FLAGS: >-
    -std=c11
    -g
    -Wall
    -Wextra
    -Werror
    -Wconversion
    -pedantic
    -fsanitize=address
    -I{{.ROOT_DIR}}

includes:
  bigint:
    taskfile: ./bigint/Build.yml
    vars:
      OUT: ./bin/bigint
    dir: ./bigint

  lua-bigint:
    taskfile: ./lua-bigint/Build.yml
    vars:
      OUT: ./bigint.so
    dir: ./lua-bigint

  mem:
    taskfile: ./mem/Build.yml
    vars:
      OUT: ./bin/main
    dir: ./mem

  gol:
    taskfile: ./gol/Build.yml
    vars:
      OUT: ./bin/gol
    dir: ./gol

tasks:
  fix-whitespace:
    desc: Remove trailing whitespace from all project files.
    deps:
      - task: find-and-replace
        vars:
          VIM_PATTERN: '\s\+$'
          VIM_REPLACE: ''

  # https://github.com/crimeraaa/lulu/blob/16cf4f5d187546704e7f66c9c401d85c4a71b68a/Taskfile.yml#L95C8-L95C11
  find-and-replace:
    desc: Replace a pattern in all project files. Uses Vim syntax.
    vars:
      VIM: vim
      VIM_GLOB: ./**/*.*

      # Dissection:
      #   -e
      #     Ex mode, used mainly for non-interactive file editing.
      #
      #   -u NONE
      #     Do not load .vimrc nor init.vim of any kind.
      #
      #   -c <command>
      #     Execute <command> after entering. Multiple instances of this
      #     can be chained.
      #
      #   -- <...>
      #     Positional arguments: file names or globs thereof.
      VIM_FLAGS: >-
        -e
        -u NONE
        -c ':bufdo! %s/{{.VIM_PATTERN}}/{{.VIM_REPLACE}}/ge'
        -c ':xa'
    prompt: This command will potentially modify all project files. Continue?
    cmds:
      - '{{.VIM}} {{.VIM_FLAGS}} {{.VIM_GLOB}}'
    requires:
      vars: [VIM_PATTERN, VIM_REPLACE]
    preconditions:
      - sh: command -v {{.VIM}}
