#include "chars.h"

#define TRAITS_SPACE_CNTRL     (CHAR_CNTRL | CHAR_SPACE)
#define TRAITS_PUNCT           (CHAR_PRINT | CHAR_GRAPH | CHAR_PUNCT)
#define TRAITS_UPPER           (CHAR_PRINT | CHAR_GRAPH | CHAR_UPPER)
#define TRAITS_UPPER_XDIGIT    (TRAITS_UPPER | CHAR_XDIGIT)
#define TRAITS_LOWER           (CHAR_PRINT | CHAR_GRAPH | CHAR_LOWER)
#define TRAITS_LOWER_XDIGIT    (TRAITS_LOWER | CHAR_XDIGIT)

/** @link https://en.cppreference.com/w/c/string/byte/isalpha.html */
const u16
ASCII_CHAR_TRAITS[CHAR_MAX + 1] = {
    // Control Codes (NUL, etc.)
    CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL,
    CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL,

    // Tab, Whitespaces
    TRAITS_SPACE_CNTRL | CHAR_BLANK, TRAITS_SPACE_CNTRL, TRAITS_SPACE_CNTRL,
    TRAITS_SPACE_CNTRL, TRAITS_SPACE_CNTRL,

    // Control Codes
    CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL,
    CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL,
    CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL, CHAR_CNTRL,

    // Space
    CHAR_PRINT | CHAR_SPACE | CHAR_BLANK,

    // Punctuations: !"#$%&'()*+,-./
    TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT,
    TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT,
    TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT,

    // Uppercase: ABCDEF
    TRAITS_UPPER_XDIGIT, TRAITS_UPPER_XDIGIT, TRAITS_UPPER_XDIGIT,
    TRAITS_UPPER_XDIGIT, TRAITS_UPPER_XDIGIT, TRAITS_UPPER_XDIGIT,

    // Uppercase: GHIJKLMNOPQRSTUVWXYZ
    TRAITS_UPPER, TRAITS_UPPER, TRAITS_UPPER, TRAITS_UPPER, TRAITS_UPPER,
    TRAITS_UPPER, TRAITS_UPPER, TRAITS_UPPER, TRAITS_UPPER, TRAITS_UPPER,
    TRAITS_UPPER, TRAITS_UPPER, TRAITS_UPPER, TRAITS_UPPER, TRAITS_UPPER,
    TRAITS_UPPER, TRAITS_UPPER, TRAITS_UPPER, TRAITS_UPPER, TRAITS_UPPER,

    // Punctuations: [\]^_`
    TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT,
    TRAITS_PUNCT,

    // Lowercase: acbdef
    TRAITS_LOWER_XDIGIT, TRAITS_LOWER_XDIGIT, TRAITS_LOWER_XDIGIT,
    TRAITS_LOWER_XDIGIT, TRAITS_LOWER_XDIGIT, TRAITS_LOWER_XDIGIT,

    // Lowercase: ghijklmnopqrstuvwxyz
    TRAITS_LOWER, TRAITS_LOWER, TRAITS_LOWER, TRAITS_LOWER, TRAITS_LOWER,
    TRAITS_LOWER, TRAITS_LOWER, TRAITS_LOWER, TRAITS_LOWER, TRAITS_LOWER,
    TRAITS_LOWER, TRAITS_LOWER, TRAITS_LOWER, TRAITS_LOWER, TRAITS_LOWER,
    TRAITS_LOWER, TRAITS_LOWER, TRAITS_LOWER, TRAITS_LOWER, TRAITS_LOWER,

    // Punctuation: {|}~
    TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT, TRAITS_PUNCT,

    // Backspace Character (DEL)
    CHAR_CNTRL,
};

// Macro cleanup
#undef TRAITS_SPACE_CNTRL
#undef TRAITS_PUNCT
#undef TRAITS_UPPER
#undef TRAITS_UPPER_XDIGIT
#undef TRAITS_LOWER
#undef TRAITS_LOWER_XDIGIT
