# https://taskfile.dev

version: '3'

vars:
  OUT: ./bin/lulu
  VET_FLAGS: -vet -vet-packages:lulu -vet-unused-procedures -vet-using-param
  FLAGS: >-
    -debug
    -sanitize=address
    -out:"{{.OUT}}"
    -define:LULU_DISASSEMBLE_CHUNK=true
    -define:LULU_DISASSEMBLE_INLINE=true

tasks:
  run:
    desc: Build the `lulu` executable unconditionally and run it.
    deps:
      - task: build
    cmds:
      - '{{.OUT}} {{.CLI_ARGS}}'
    interactive: true

  build:
    desc: Build the `lulu` executable unconditionally.
    cmds:
      - mkdir -p bin
      - odin build {{.TASKFILE_DIR}}/ {{.FLAGS}}
    sources:
      - '{{.TASKFILE_DIR}}/*.odin'
      - '{{.TASKFILE_DIR}}/lulu/**/*.odin'
